[project]
name = "prefix-opener"
version = "0.1.0"
description = "Search and open Steam Proton prefixes"
readme = "README.md"
license = "GPL-3.0-only"
authors = [
    { name = "Francesco", email = "chiccocarone@gmail.com" }
]
requires-python = ">=3.11"
dependencies = [
    "rich>=14.2.0",
    "textual>=8.2.8",
    "typer>=0.27.0",
]

[project.scripts]
prefix-opener = "prefix_opener:main"

[build-system]
requires = ["uv_build>=0.11.32,<0.13.0"]
build-backend = "uv_build"
